### ISSUE TITLE
bar_plot function doesn't write pdf file

### ISSUE THREAD

**Issue by soluna1** [trtcrd/POGO_ML_workshop_genomics#1]
Hi Tristan, 

I was one of the participants in the last ML POGO course. I have a small issue when trying to write down the pdf files from bar_plot custom function. The plot is displayed correctly and opened in Quarz, but for some unknown reason the pdf file is corrupted. Should it be some silly thing with my computer configuration? I'm working on a Macbook pro os 10.13.6, R version 3.6.0 (2019-04-26). 
Thanks for your help.

**Comment by trtcrd** [comment]
Hi, 
Sorry to have been so long to reply.
This is strange and hard to say, with what are you opening your pdf, acrobat reader? Did you try to open the file on a different computer? Is it really corrupted?
